# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    - cat docs/environment-py38-rtd.yml
    - conda env create --quiet --name latest --file docs/environment-py38-rtd.yml
    - conda activate latest
    - python setup.py build_ext --force --inplace
    - python setup.py install
    - cat docs/conf.py
    - python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html

conda:
  environment: docs/environment-py38-rtd.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
