# Required
version: 2

conda:
  environment: docs/environment-py38-rtd.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    pre_install:
      - python setup.py build_ext --force --inplace

python:
  install:
    - method: setuptools
      path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
